### PR TITLE
Adding a license file

### PR DESCRIPTION
**Pull request by brendan98**
what do you think of this?  should we use the MIT license or something else?

### CODE REVIEW

**Comment by Massinja** [comment]
That's a great idea! However, in my family we only support GPLv3+. Could you redo that? thanks!

**Comment by brendan98** [comment]
lol and we're already in a rebase situation.  ok let me see if I can clean this up.

**Comment by brendan98** [comment]
I see the GPLv3, but I don't see GPLv3+.  is that a separate license?  it didn't come up in the github template list.

**Comment by Massinja** [comment]
Yes, it's version 3 or any later one that will come out.

**Comment by brendan98** [comment]
updated license and merged the readme.  what do you think?

**Comment by brendan98** [comment]
ok wait, so it's still not right.  hold on.

**Pull request closed without merging**
